% =========================================================
% COMSOL 6.3 LiveLink for MATLAB — Pressure Acoustics
% Auto-generated by COMSOL AI Simulation System
% Physics : Pressure Acoustics, Frequency Domain (2-D)
% =========================================================
import com.comsol.model.*
import com.comsol.model.util.*

% --- Connect to COMSOL Server ---
addpath('%%COMSOL_MLI_PATH%%');
mphstart(%%COMSOL_PORT%%);

fprintf('=== COMSOL Acoustic Simulation Starting ===\n');
fprintf('Room   : %%ROOM_LENGTH%% x %%ROOM_WIDTH%% m\n');
fprintf('Source : (%%SRC_X%%, %%SRC_Y%%) m | f = %%FREQUENCY%% Hz\n');

outputDir = '%%OUTPUT_DIR%%';
if ~exist(outputDir, 'dir'), mkdir(outputDir); end

% --- Create Model ---
model = ModelUtil.create('AcousticModel');
model.modelPath(outputDir);

% --- Component ---
model.component.create('comp1', true);

% --- 2-D Geometry ---
model.component('comp1').geom.create('geom1', 2);

% Room rectangle
model.component('comp1').geom('geom1').create('r1', 'Rectangle');
model.component('comp1').geom('geom1').feature('r1').set('width',  %%ROOM_LENGTH%%);
model.component('comp1').geom('geom1').feature('r1').set('height', %%ROOM_WIDTH%%);

% Source point (interior)
model.component('comp1').geom('geom1').create('pt1', 'Point');
model.component('comp1').geom('geom1').feature('pt1').set('p', [%%SRC_X%%; %%SRC_Y%%]);

model.component('comp1').geom('geom1').run('fin');
fprintf('Geometry created.\n');

% --- Material: Air ---
model.component('comp1').material.create('mat1', 'Common');
model.component('comp1').material('mat1').label('Air');
model.component('comp1').material('mat1').selection.all;
model.component('comp1').material('mat1').propertyGroup('def').set('density',    {'1.225'});
model.component('comp1').material('mat1').propertyGroup('def').set('soundspeed', {'343'});

% --- Physics: Pressure Acoustics, Frequency Domain ---
model.component('comp1').physics.create('acpr', 'PressureAcoustics', 'geom1');

% Monopole point source at the interior point
% Note: point index depends on geometry; typically index 5 for first interior point.
% If this fails, open the model in COMSOL GUI to confirm the correct point index.
model.component('comp1').physics('acpr').create('mono1', 'MonopolePointSource', 0);
model.component('comp1').physics('acpr').feature('mono1').selection.set([5]);
model.component('comp1').physics('acpr').feature('mono1').set('Qs', %%SOURCE_POWER%%);

% All exterior boundaries: Sound Hard (Rigid Wall) — default, no action needed

fprintf('Physics set.\n');

% --- Mesh ---
% Rule of thumb: >= 6 elements per wavelength
% lambda = 343 / f => for safety use autoMeshSize driven by physics
model.component('comp1').mesh.create('mesh1');
model.component('comp1').mesh('mesh1').automatic(true);
model.component('comp1').mesh('mesh1').autoMeshSize(%%MESH_SIZE%%);
model.component('comp1').mesh('mesh1').run;
fprintf('Mesh created.\n');

% --- Study: Frequency Domain ---
model.study.create('std1');
model.study('std1').create('freq', 'Frequency');
model.study('std1').feature('freq').set('plist', %%FREQUENCY%%);

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').attach('std1');
model.sol('sol1').runAll;
fprintf('Solver finished.\n');

% --- Plot: Sound Pressure Level ---
model.result.create('pg1', 'PlotGroup2D');
model.result('pg1').label('Sound Pressure Level');
model.result('pg1').set('data', 'dset1');
model.result('pg1').create('surf1', 'Surface');
model.result('pg1').feature('surf1').set('expr',       'acpr.Lp');
model.result('pg1').feature('surf1').set('descr',      'Sound pressure level (dB)');
model.result('pg1').feature('surf1').set('colortable', 'Wave');

model.result.export.create('img1', 'Image2D');
model.result.export('img1').set('plotgroup', 'pg1');
model.result.export('img1').set('filename',  fullfile(outputDir, 'spl_field.png'));
model.result.export('img1').set('size',      'manualweb');
model.result.export('img1').set('unit',      'px');
model.result.export('img1').set('height',    '800');
model.result.export('img1').set('width',     '1000');
model.result.export('img1').run;

% --- Plot: Acoustic Pressure (real part) ---
model.result.create('pg2', 'PlotGroup2D');
model.result('pg2').label('Acoustic Pressure');
model.result('pg2').set('data', 'dset1');
model.result('pg2').create('surf1', 'Surface');
model.result('pg2').feature('surf1').set('expr',       'real(p)');
model.result('pg2').feature('surf1').set('descr',      'Acoustic pressure, real part (Pa)');
model.result('pg2').feature('surf1').set('colortable', 'Wave');

model.result.export.create('img2', 'Image2D');
model.result.export('img2').set('plotgroup', 'pg2');
model.result.export('img2').set('filename',  fullfile(outputDir, 'pressure_field.png'));
model.result.export('img2').set('size',      'manualweb');
model.result.export('img2').set('unit',      'px');
model.result.export('img2').set('height',    '800');
model.result.export('img2').set('width',     '1000');
model.result.export('img2').run;

% --- Save ---
model.save(fullfile(outputDir, 'acoustic_model.mph'));
fprintf('=== Done. Results: %s ===\n', outputDir);
