% =========================================================
% COMSOL 6.3 LiveLink for MATLAB — Laminar Flow Simulation
% Auto-generated by COMSOL AI Simulation System
% Physics : Single Phase Flow (Laminar), 2-D Axisymmetric
% =========================================================
import com.comsol.model.*
import com.comsol.model.util.*

% --- Connect to COMSOL Server ---
addpath('%%COMSOL_MLI_PATH%%');
mphstart(%%COMSOL_PORT%%);

fprintf('=== COMSOL Flow Simulation Starting ===\n');
fprintf('Pipe  : Length = %%LENGTH%% m | Radius = %%RADIUS%% m\n');
fprintf('Fluid : rho = %%DENSITY%% kg/m^3 | mu = %%VISCOSITY%% Pa*s\n');
fprintf('BC    : inlet velocity = %%INLET_VELOCITY%% m/s\n');

outputDir = '%%OUTPUT_DIR%%';
if ~exist(outputDir, 'dir'), mkdir(outputDir); end

% --- Create Model ---
model = ModelUtil.create('FlowModel');
model.modelPath(outputDir);

% --- Component ---
model.component.create('comp1', true);

% --- 2-D Axisymmetric Geometry ---
% r-z plane: width = radius, height = length
model.component('comp1').geom.create('geom1', 2);
model.component('comp1').geom('geom1').axisymmetric(true);

model.component('comp1').geom('geom1').create('r1', 'Rectangle');
model.component('comp1').geom('geom1').feature('r1').set('width',  %%RADIUS%%);
model.component('comp1').geom('geom1').feature('r1').set('height', %%LENGTH%%);
model.component('comp1').geom('geom1').run('fin');

% Boundary numbering (Rectangle, axisymmetric):
%   1 = bottom  (z = 0)      -> INLET
%   2 = right   (r = R)      -> WALL (no-slip, default)
%   3 = top     (z = L)      -> OUTLET
%   4 = left    (r = 0)      -> SYMMETRY AXIS (auto)

fprintf('Geometry created.\n');

% --- Material ---
model.component('comp1').material.create('mat1', 'Common');
model.component('comp1').material('mat1').label('Fluid');
model.component('comp1').material('mat1').selection.all;
model.component('comp1').material('mat1').propertyGroup('def').set('density',         {num2str(%%DENSITY%%)});
model.component('comp1').material('mat1').propertyGroup('def').set('dynamicviscosity', {num2str(%%VISCOSITY%%)});

% --- Physics: Laminar Flow ---
model.component('comp1').physics.create('spf', 'LaminarFlow', 'geom1');

% Inlet  (boundary 1)
model.component('comp1').physics('spf').create('inl1', 'InletBoundary', 1);
model.component('comp1').physics('spf').feature('inl1').selection.set([1]);
model.component('comp1').physics('spf').feature('inl1').set('BoundaryCondition', 'UniformVelocity');
model.component('comp1').physics('spf').feature('inl1').set('U0', %%INLET_VELOCITY%%);

% Outlet (boundary 3) — zero gauge pressure by default
model.component('comp1').physics('spf').create('out1', 'OutletBoundary', 1);
model.component('comp1').physics('spf').feature('out1').selection.set([3]);

fprintf('Physics set.\n');

% --- Mesh ---
model.component('comp1').mesh.create('mesh1');
model.component('comp1').mesh('mesh1').automatic(true);
model.component('comp1').mesh('mesh1').autoMeshSize(%%MESH_SIZE%%);
model.component('comp1').mesh('mesh1').run;
fprintf('Mesh created.\n');

% --- Study: Stationary ---
model.study.create('std1');
model.study('std1').create('stat', 'Stationary');

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').attach('std1');
model.sol('sol1').runAll;
fprintf('Solver finished.\n');

% --- Plot: Velocity ---
model.result.create('pg1', 'PlotGroup2D');
model.result('pg1').label('Velocity Magnitude');
model.result('pg1').set('data', 'dset1');
model.result('pg1').create('surf1', 'Surface');
model.result('pg1').feature('surf1').set('expr',       'spf.U');
model.result('pg1').feature('surf1').set('descr',      'Velocity magnitude (m/s)');
model.result('pg1').feature('surf1').set('colortable', 'RainbowLight');
model.result('pg1').create('arw1', 'Arrow2D');
model.result('pg1').feature('arw1').set('expr',  {'u' 'v'});
model.result('pg1').feature('arw1').set('scale', 'auto');

model.result.export.create('img1', 'Image2D');
model.result.export('img1').set('plotgroup', 'pg1');
model.result.export('img1').set('filename',  fullfile(outputDir, 'velocity_field.png'));
model.result.export('img1').set('size',      'manualweb');
model.result.export('img1').set('unit',      'px');
model.result.export('img1').set('height',    '800');
model.result.export('img1').set('width',     '1000');
model.result.export('img1').run;

% --- Plot: Pressure ---
model.result.create('pg2', 'PlotGroup2D');
model.result('pg2').label('Pressure');
model.result('pg2').set('data', 'dset1');
model.result('pg2').create('surf1', 'Surface');
model.result('pg2').feature('surf1').set('expr',       'p');
model.result('pg2').feature('surf1').set('descr',      'Pressure (Pa)');
model.result('pg2').feature('surf1').set('colortable', 'Thermal');

model.result.export.create('img2', 'Image2D');
model.result.export('img2').set('plotgroup', 'pg2');
model.result.export('img2').set('filename',  fullfile(outputDir, 'pressure_field.png'));
model.result.export('img2').set('size',      'manualweb');
model.result.export('img2').set('unit',      'px');
model.result.export('img2').set('height',    '800');
model.result.export('img2').set('width',     '1000');
model.result.export('img2').run;

% --- Export Centerline CSV (axis boundary 4, r = 0) ---
model.result.numerical.create('lne1', 'Line');
model.result.numerical('lne1').label('Centerline');
model.result.numerical('lne1').selection.set([4]);
model.result.numerical('lne1').set('expr',    {'v'                   'p'});
model.result.numerical('lne1').set('descr',   {'Axial velocity (m/s)' 'Pressure (Pa)'});
model.result.export.create('data1', 'Data');
model.result.export('data1').set('numpoints', 200);
model.result.export('data1').set('filename',  fullfile(outputDir, 'centerline_data.csv'));
model.result.export('data1').run;

% --- Save ---
model.save(fullfile(outputDir, 'flow_model.mph'));
fprintf('=== Done. Results: %s ===\n', outputDir);
